drop table if exists ss_task;
drop table if exists ss_user;


create table ss_team (
  	id bigint generated by default as identity,
	name varchar(255) not null unique,
	master_id bigint,
    primary key (id)
);

insert into ss_team (id, name, master_id) values(1,'Dolphin',1);